# Development version of the beyla Dockerfile that compiles for coverage
# and allows retrieving coverage files.
# The production-ready minimal image is in the project root's dockerfile.
FROM golang:1.27.0@sha256:0ecdc2a9f6156af6451080bfe3d8382a662fcc4e209608c6f919e643453514c1 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /

COPY internal/test/integration/components/obi/ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /src

# Copy the go manifests and source
COPY .git/ .git/
COPY bpf/ bpf/
COPY cmd/ cmd/
COPY internal/goabi/ internal/goabi/
COPY internal/goversion/ internal/goversion/
COPY internal/config/ internal/config/
COPY pkg/ pkg/
COPY go.mod go.mod
COPY go.sum go.sum

# Build
RUN mkdir -p bin && CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -cover -o bin/obi cmd/obi/main.go

FROM scratch

# Copy the native executable into the containers
COPY --from=builder /src/bin/obi /obi
COPY --from=builder /ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /

ENTRYPOINT [ "/ebpf_instrument_wrapper.sh" ]
