#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root/internal/test/integration/components/old_grpc/worker"
protoc --go_out=. --go-grpc_out=. proto/service.proto
