// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

/*
generate-port-lookup reads the default /etc/services spec
from the https://github.com/openbsd/src repository
and generates a Go file (protocol.go by default)
with a lookup table mapping well-known ports
to service names for use by the transport package.

Usage:

	generate-port-lookup [flags]

The flags are:

	-dst filepath
		Destination file path for generated code (default "protocol.go")
*/
package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"strconv"
	"strings"
	"text/template"
)

const fileTemplate = `// Code generated by generate-port-lookup; DO NOT EDIT.

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Generated using services definition from
// {{ .ServicesURL }}
//
// To regenerate it, manually run:
// $ mise run regenerate-port-lookup

package transport // import "go.opentelemetry.io/obi/pkg/internal/netolly/flow/transport"

var generatedPortLookupTable = map[uint16]string{
{{- range $port, $svc := .Services }}
	{{ $port }}: "{{ $svc }}",
{{- end }}
}

func ApplicationPortToString(port uint16) string {
	svc := generatedPortLookupTable[port]
	if svc == "" {
		return "undefined"
	}
	return svc
}
`

// servicesUrl currently points to the /etc/services file of the OpenBSD project.
// It offers a stable base and is permissively licensed.
const ServicesURL = "https://raw.githubusercontent.com/openbsd/src/28304016fe9353c375bc53e9b3d5bb67585d6a2a/etc/services"

var protocolsFile = flag.String("dst", "protocol.go", "destination file path for generated code")

func requiresRegeneration(servicesURL string) bool {
	existing, err := os.Open(*protocolsFile)
	if err != nil {
		slog.Warn("unable to open existing file, forcing rebuild", "err", err)
		return true
	}
	defer existing.Close()
	content, err := io.ReadAll(existing)
	if err != nil {
		slog.Warn("unable to read contents of existing file, forcing rebuild", "err", err)
		return true
	}
	return !strings.Contains(string(content), servicesURL)
}

func parseServices(r io.Reader) (map[int]string, error) {
	s := bufio.NewScanner(r)
	mapping := make(map[int]string)
	for lineNum := 1; s.Scan(); lineNum++ {
		line := s.Text()
		if strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}

		port, protocol, ok := strings.Cut(fields[1], "/")
		if !ok || port == "" || protocol == "" {
			return nil, fmt.Errorf("malformed services entry on line %d: %q", lineNum, line)
		}

		n, err := strconv.Atoi(port)
		if err != nil {
			continue
		}

		if protocol == "udp" || protocol == "tcp" {
			mapping[n] = fields[0]
		}
	}

	if err := s.Err(); err != nil {
		return nil, err
	}
	if len(mapping) == 0 {
		return nil, errors.New("services response did not contain any tcp or udp entries")
	}

	return mapping, nil
}

func fetchServices(client *http.Client, url string) (map[int]string, error) {
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected services response status: %s", resp.Status)
	}

	return parseServices(resp.Body)
}

func run(client *http.Client, servicesURL string) error {
	if !requiresRegeneration(servicesURL) {
		slog.Info("protocol file is up to date, skipping generation")
		return nil
	}
	slog.Info("reading services file")
	mapping, err := fetchServices(client, servicesURL)
	if err != nil {
		return fmt.Errorf("failed to read services file: %w", err)
	}
	slog.Info("finished reading service file", "detected_services", len(mapping))

	tmpl, err := template.New("protocol.go").Parse(fileTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(*protocolsFile)
	if err != nil {
		return fmt.Errorf("failed to open file for writing: %w", err)
	}
	defer f.Close()
	if err := tmpl.Execute(f, map[string]any{
		"ServicesURL": servicesURL,
		"Services":    mapping,
	}); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}
	slog.Info("finished generating service lookup code")

	return nil
}

func main() {
	flag.Parse()

	if err := run(http.DefaultClient, ServicesURL); err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
}
