#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root/pkg/internal/transform/route/harvest/dotnet/testdata"
dotnet build --configuration Release --output bin -p:BaseIntermediateOutputPath=bin/obj/ routes.csproj
base64 --wrap=96 bin/routes.dll > routes.dll.b64
